export const actionType = {
  ADD_TO_WATCHLIST: "ADD_TO_WATCHLIST",
  ADD_MOVIE: "ADD_MOVIE",
  ADJUST_MOVIE_QTY: "ADJUST_MOVIE_QTY",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  VIEW_SINGLE_MOVIE: "VIEW_SINGLE_MOVIE",
};
